### ISSUE TITLE
Database Details?

### ISSUE THREAD

**Issue by infrabyte** [ionutvmi/master-comments-system#7]
Hi. What would the database need to look like? eg:
db name = test
table1 = ?
table2 = ?
col1 = ?
etc

**Comment by mihai-vlc** [comment]
the database schema is here: https://github.com/ionutvmi/master-comments-system/blob/master/comments.class.php#L416

**Comment by infrabyte** [comment]
Thank you very much. For some reason I missed that. Looking good.

**Comment by infrabyte** [comment]
one last thing. When I try post a comment I get "Some error camed up !" How do you register a user?
Or how do you log in to post? Or must this be running under Wordpress? I am running it 'standalone' in my /var/www/html using Apache/2.4.29 and PHP 7.2.11-3

All I have is as seen attached.
![screenshot from 2018-10-29 09-47-02](https://user-images.githubusercontent.com/11523032/47636032-acaa0600-db5f-11e8-8dd4-4788052b0e02.png)

**Comment by mihai-vlc** [comment]
For the registered user you will need a separate system to keep track of them.
When you initialize the comments class you can provide the user details.
Example here: https://github.com/ionutvmi/master-comments-system/blob/master/registered_user.php#L41
