### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by OoLunar** [ionutvmi/master-comments-system#9]
Hey!
I probably missed the instructions somewhere, or I've messed something up. Exactly how do I install this? It looks incredible (sounds like it too), but I have no clue how to get this working. With no errors in the error console, and nothing to see for a blind eye, I'm completely lost. I did notice that you have us using the "test" database on MySQL, but I _accidentally_ deleted it, and I have no knowledge with MySQL. Can you give me step-by-step instructions on how to get everything up and working please?

**Comment by mihai-vlc** [comment]
The installation happens automatically if you pass the auto_install flag (default true).
https://github.com/ionutvmi/master-comments-system/blob/master/comments.class.php#L65

Before calling this code you need to ensure that the database exists. It doesn't have to be named `test`.

**Comment by OoLunar** [comment]
![image](https://user-images.githubusercontent.com/46751150/57174192-64b2b700-6e00-11e9-9461-524b81dd9637.png)

Alright. The flag is enabled, I've cleared my root password, and I haven't touched any other file. There's no error in the Chrome Dev Tools, and yet my comment section is still playing hide and seek with me. Any other clues of what to do?
Edit: Using MySQL version 5.7, if that's a problem.

**Comment by mihai-vlc** [comment]
Try to debug it and see if it gets to the install method.
You should validate that the DB credentials are correct and the permissions for your mysql user.

**Comment by OoLunar** [comment]
I have given ALL permissions to my user, and I am 100% positive that my DB cred are correct. Just found the error:
Fatal error: Uncaught Error: Call to undefined function mysqli_connect() in \<path\>/media/music/requests/comments.class.php:54 Stack trace: #0 \<path\>/media/music/requests/index.php(81): Comments_System->__construct(Array) #1 {main} thrown in \<path\>media/music/requests/comments.class.php on line 54

**Comment by OoLunar** [comment]
Just installed ``php7.0-mysql``, still having the same error

**Comment by OoLunar** [comment]
GOT IT! I had to download the php extension of mysql, then enable it in my php.ini Thanks for all the support!
